import torch
import pandas as pd
import numpy as np
from transformers import AutoTokenizer, AutoModelForCausalLM
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, f1_score
from tqdm import tqdm

# ==========================================
# 1. INITIALIZE INFRASTRUCTURE
# ==========================================
model_id = "meta-llama/Llama-3.2-3B"
tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.float16, device_map="auto")

# Activation hook setup
extracted_activations = {}
def residual_stream_hook(module, input, output):
    extracted_activations["hidden_states"] = output[0].detach().cpu()

# Register hook to your choice middle layer (e.g., Layer 12)
target_layer = model.model.layers[12]
hook_handle = target_layer.register_forward_hook(residual_stream_hook)

# Map text labels to integers for sklearn processing
LABEL_MAP = {"fact": 0, "implication": 1, "negation": 2}

# ==========================================
# 2. DEFINE EXTRACTION ENGINE
# ==========================================
def extract_features_from_split(csv_path, split_name="Split"):
    """Reads a split CSV, runs forward passes, and returns X (vectors) and Y (labels)."""
    df = pd.read_csv(csv_path)
    
    X_list = []
    Y_list = []
    
    # Wrap the dataframe iterator with tqdm to create a visual progress bar
    progress_description = f"Extracting {split_name:<5}"
    for idx, row in tqdm(df.iterrows(), total=len(df), desc=progress_description, unit="sentence"):
        sentence = row["Sentence"]
        label_str = row["Label"]
        
        # Guard rail: Skip unexpected rows or missing data
        if pd.isna(sentence) or label_str not in LABEL_MAP:
            continue
            
        # Tokenize sequence
        inputs = tokenizer(sentence, return_tensors="pt")
        inputs = {k: v.to(model.device) for k, v in inputs.items()}
        
        # Execute localized forward pass (bypassing expensive token generation loop)
        with torch.no_grad():
            model(**inputs)
            
        # Extract sequence tensor matrix: [seq_len, 3072]
        layer_hidden_states = extracted_activations["hidden_states"][0]
        
        # Execute Mean-Pooling across sequence dimension to get unified sentence embedding
        mean_pooled_vector = torch.mean(layer_hidden_states, dim=0).numpy()
        
        X_list.append(mean_pooled_vector)
        Y_list.append(LABEL_MAP[label_str])
        
    return np.array(X_list), np.array(Y_list)

# ==========================================
# 3. RUN MACHINE LEARNING LIFECYCLE
# ==========================================
if __name__ == "__main__":
    # Point these to the CSV splits generated by your data compilation pipeline
    X_train, y_train = extract_features_from_split("./data/logicnli_probing_targets-train.csv")
    X_dev, y_dev = extract_features_from_split("./data/logicnli_probing_targets-dev.csv")
    X_test, y_test = extract_features_from_split("./data/logicnli_probing_targets-test.csv")

    # ------------------------------------------
    # Phase A: Train Probe on Calibration Split
    # ------------------------------------------
    print("\nTraining Linear Probe...")
    probe = LogisticRegression(C=1.0, penalty='l2', max_iter=1000)
    probe.fit(X_train, y_train)
    
    # ------------------------------------------
    # Phase B: Validate on Dev Split (Hyperparameter check)
    # ------------------------------------------
    dev_preds = probe.predict(X_dev)
    dev_f1 = f1_score(y_dev, dev_preds, average='macro')
    print(f"Validation (Dev Split) Macro F1-Score: {dev_f1:.4f}")
    
    # Note: If dev_f1 is low, your script would loop through different layers 
    # (e.g., testing layer 8 vs 14) before freezing the configuration.
    
    # ------------------------------------------
    # Phase C: Final Evaluation on Unseen Test Split
    # ------------------------------------------
    print("\n=== FINAL TEST EVALUATION ===")
    test_preds = probe.predict(X_test)
    
    # Print clear, publication-grade metrics for your thesis
    print(classification_report(
        y_test, 
        test_preds, 
        target_names=list(LABEL_MAP.keys())
    ))
    
    # Clean up the hook memory reference when finished
    hook_handle.remove()